version: '1.0.4-build{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/ben-foster-cko-dev/api/v2/package
  api_key:
    secure: cywvUXN90tLAa82KXWVO2G14C1aWvlgrpgxpL7i2oALjKtenX3YGPxyIQUlNbiAM
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  server: https://www.myget.org/F/ben-foster-cko/api/v2/package
  api_key:
    secure: cywvUXN90tLAa82KXWVO2G14C1aWvlgrpgxpL7i2oALjKtenX3YGPxyIQUlNbiAM
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
